apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "matchverification-deployment-config-jhye"
  namespace: "default"
  labels:
    app: "matchverification-deployment"
data:
  ENV: "DEV"
  DEV_QUESTION_API_URL: "http://question:3003/api/question"
  DEV_REDIS_HOST: "redis"
  DEV_REDIS_PORT: "6379"
  DEV_KAFKA_URL: "kafka-service:9092"
