version: "3"

services:
  frontend:
    build:
      context: ./peerprep_fe
      dockerfile: Dockerfile.dev
    volumes:
      - ./peerprep_fe:/app
      - /app/node_modules
    environment:
      - FRONTEND_PORT=${FRONTEND_PORT}
    ports:
      - "3000:3000"

  gateway-service:
    build:
      context: ./gateway_service
      dockerfile: Dockerfile.dev
    volumes:
      - ./gateway_service:/app
      - /app/node_modules
    environment:
      - API_GATEWAY_PORT=${API_GATEWAY_PORT}
      - USER_SERVICE_PORT=${USER_SERVICE_PORT}
      - QUESTION_SERVICE_PORT=${QUESTION_SERVICE_PORT}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "5003:5003"

  user-service:
    build:
      context: ./users_service
      dockerfile: Dockerfile.dev
    volumes:
      - ./users_service:/app
      - /app/node_modules # This prevents the host's node_modules from overwriting the container's
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - USER_SERVICE_PORT=${USER_SERVICE_PORT}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "5001:5001"

  question-service:
    build:
      context: ./question_service
      dockerfile: Dockerfile.dev
    volumes:
      - ./question_service:/app
      - /app/node_modules # This prevents the host's node_modules from overwriting the container's
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - QUESTION_SERVICE_PORT=${QUESTION_SERVICE_PORT}
    ports:
      - "5002:5002"
