apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: room-service
  name: room-service
  namespace: g55
spec:
  replicas: 1
  selector:
    matchLabels:
      app: room-service
  template:
    metadata:
      labels:
        app: room-service
    strategy:
      type: Recreate
    spec:
      containers:
        - image: docker_username/room_service:latest
          imagePullPolicy: IfNotPresent
          name: room-service
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
      restartPolicy: Always
status: {}
