apiVersion: apps/v1
kind: Deployment
metadata: 
  name: peerprep-fe
  labels:
    type: frontend
    app: peerprep-fe
spec:
  selector:
    matchLabels:
      type: frontend
      app: peerprep-fe
  template:
    metadata:
      name: peerprep-fe
      labels:
        type: frontend
        app: peerprep-fe
    spec:
      containers:
      - name: peerprep-fe
        image: asia-southeast1-docker.pkg.dev/cs3219-g11-peerprep/cs3219-g11-repo/peerprep-fe:latest
        # imagePullPolicy: Never # only used for local builds
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: peerprep-fe
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
  selector:
    type: frontend
    app: peerprep-fe
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: peerprep-fe
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: peerprep-fe
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
