# Command: docker-compose --env-file .env.local up -d

services:
  user-db:
    hostname: "user-db"
    image: postgres:16.4
    container_name: "user-db"
    build:
      context: ./src/lib/db
    env_file:
      - ./.env.local
    volumes:
      - "user-db-docker:${PGDATA}"
      #  - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "${EXPRESS_DB_PORT}:5432"
    restart: unless-stopped

  user-express:
    image: "user-express"
    container_name: "user-express"
    build:
      context: ./
      dockerfile: ./express.Dockerfile
      target: build
      args: 
        # For building with the correct env vars
        - env=${EXPRESS_ENV}
        - port=${EXPRESS_PORT}
    ports:
      - "9001:${EXPRESS_PORT}"
    command: node dist/index.js
    env_file:
      - ./.env.local
    environment:
      # Docker Compose Specific
      - EXPRESS_DB_HOST=user-db
      - EXPRESS_DB_PORT=5432
    depends_on:
      - user-db
  
volumes:
  user-db-docker: