apiVersion: v1
kind: Secret
metadata:
  name: secrets
  namespace: peer-prep
type: Opaque
stringData:
  # All fields to be filled in
  user_svc_db_uri: 
  question_svc_db_uri: 
  collab_svc_db_uri: 
  jwt_secret: 
  user_svc_email_address: 
  user_svc_email_password: 
  openai_api_key: 
