apiVersion: apps/v1
kind: Deployment
metadata:
  name: question-service
  namespace: peer-prep
  labels:
    app: question-service
spec:
  selector:
    matchLabels:
      app: question-service
  template:
    metadata:
      labels:
        app: question-service
    spec:
      containers:
      - name: question-service
        image: jq1836/cs3219-g50-question-service:latest
        env:
        - name: DB_URI
          valueFrom:
            secretKeyRef:
              name: secrets
              key: question_svc_db_uri
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
      restartPolicy: Always
